name: SAST using Go
on: 
  push:
    branches:
      - main 
jobs:
  Analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-verion: '1.21'
      - name: Installing Go Scanner
        run: go install github.com/securego/gosec/v2/cmd/gosec@latest
      - name: Scanning the Code
        run: ~/go/bin/gosec -fmt=json -out=gosec-report.json ./...
      - name: Upload Gosec JSON Report
        uses: actions/upload-artifact@v4
        with:
          name: gosec-json-report
          path: gosec-report.json
